### PR TITLE
GList output support

### PR DESCRIPTION
**Pull request by LordYuuma**

### CODE REVIEW

**Comment by LordYuuma** [comment]
I'm not really sure, what causes Travis to fail in make check. The failing testcases should be skipped, but somehow they are not.

**Comment by spk121** [comment]
Looks good to me.  When I get a chance, I want to try it out with gtk_application_get_windows, which is the first list-using function that shows up in Gtk+3's sample applications.

Not obvious to me why Travis is complaining, either.  Well, it is complaining about the lack of Grilo, but, I'm not sure what its exact complaint is.  There is probably a way of echoing the test-suite.log to the console during the Travis build by add a rule to make check.

**Comment by spk121** [comment]
Let me take the task of figuring out the Travis problem.  Otherwise, I'm going to be working on the doc autogeneration for a couple of days.

**Comment by LordYuuma** [comment]
Just a heads up, object lists are not yet implemented, neither are object arrays (the exception being object GArrays, where the object is memcpy'd into a bytearray, which should actually only be done for plain old data structs).

**Pull request merged**
