### PR TITLE
Build with Meson

### PR DESCRIPTION
**Pull request by LordYuuma**
Since Autotools makes it somewhat difficult to build, but not install shared objects, but GI needs shared objects to work, I've decided I'd port the build system to meson.  This also has the benefit of it being the preferred way to build GNOME stuff, and it doesn't seem to be too hard to integrate Guile.

Warning: Do not pull, before all of the following are done:
- [x] build libguile-gi
- [x] build test libraries
- [x] build introspection
- [x] (optionally) build scheme modules
- [ ] add missing options (coverage, mtrace, ...)
- [x] run simple tests
- [x] run tests requiring extra libraries + introspection
- [x] build documentation
- [x] integrate CI
- [x] update `guix.scm`
- [ ] fix broken tools or provide run targets for them
- [ ] `ninja indent` :)

### CODE REVIEW

**Comment by spk121** [comment]
The thing about meson is that it is usually not an improvement for the end user.  It is an improvement for the lives of the *developers* that do not want to deal with Autotools, but, for the downstream packager or user the benefit is limited.
For the downstream user, the pro is that `ninja` is faster than `make`, but I do not believe that the amount of time spent in `make` is very high.  Another pro is that the Windows build is easier, but, Guile 2.2 and 3.0 both don't build on Windows which makes it moot.
For the downstream user, the con is that it doesn't follow GNU coding standards for people used to the whole `./configure` thing; that `ninja` may not be familiar; and that cross-builds are somewhat more difficult.
As to your specific concern -- that test-only shared libraries get installed when they shouldn't -- I'm sure there is a workaround somewhere.  This can't be the only program that has run into that case.
Really I'm not too excited about going down this route.

**Comment by LordYuuma** [comment]
I tried both `noinst_` and `check_`, neither of which worked out pretty well.  As for meson vs. autotools, I don't really see the problem.  Most GNOME tools are built with meson, newer versions of GStreamer are too, and distros still somehow manage to ship them.  The specific group of users, who forgo package management entirely for the sake of manually running configure and make should also already be aware of this toolchain by now – or they don't use anything that requires it, including GLib >= 2.60.

Cross-builds may very well be somewhat more difficult with meson or at least sufficiently different from autotools to require more thinking on the subject.  However, it does appear as if cross-compilation setups within meson are to be described with ini-files (which imo is an easily readable and writable format).  Also, I'm not quite sure what changes for libguile-gi in a cross-compilation setup, since our CI runs in a docker container, which sounds like the opposite of a cross-compilation.

**Comment by spk121** [comment]
OK, which of these two things are you trying to accomplish
- Fixing the test shared library install problem
- Getting rid of autotools because you don't prefer autotools
If it is the former, I can fix it. It is straightforward, if slightly verbose.

**Comment by LordYuuma** [comment]
The former would probably be fine on its own.  I don't have strong feelings to any particular build system as long as they're not so exotic that distros don't ship them.

**Comment by LordYuuma** [comment]
It appears Ubuntu Bionic only ships a really outdated version of meson, that can't possibly be used to compile this (specifically, we can't filter link arguments).  I'm using eoan for the CI right now, but it appears this might really hold us up if we want to use meson on mainstream distros.

**Comment by spk121** [comment]
With regards to bionic, the Dockerfile calls out `ubuntu:latest`.  I wonder how often they update the upstream Dockerfile?
I made an attempt at fixing the problem via autotools in 8176914b0ef56838f210e7bf514440b778be4e5a

**Comment by spk121** [comment]
The lcov.sh also has weaknesses on the autotools side.  It fails when builddir does not equal srcdir, for example.

**Comment by LordYuuma** [comment]
I checked the official Ubuntu docker stuff, and it seems "latest" refers to the last LTS, with "rolling" and "devel" also existing on top of the individual release names.
Your fix appears to work, at least on Guix.  The lcov.sh thing is because you confuse the source and build directories.  I think you'd need the latter.

**Comment by LordYuuma** [comment]
Closing for now, may resurrect later.

**Pull request closed without merging**
