### PR TITLE
Make syntax less confusing (and signals slightly more verbose)

### PR DESCRIPTION
**Pull request by LordYuuma**
- `create` wraps `make-gobject` with less parentheses-heavy syntax
- `send` becomes `with-object`, which allows multiple invocations and let-binds objects, which are not already bound.
- `connect` becomes `modify-signals` which allows multiple signals to be bound, removal, (un)blocking, and connection after the main handler.
- user data is dropped

### CODE REVIEW

**Comment by spk121** [comment]
With regards to the 'send' syntax.  When I originally chose it, there were basically three pieces of prior art.

- The choice of 'send' as a syntax comes from [gi.readthedocs.io](https://gi.readthedocs.io/en/latest/writingbindings/guidelines.html) originally.
- There are the GOOPS methods, of course
`(define-method (method (var1 <type1>) (var2 <type2>))  ... )`
- From Racket, you get `(gobject-send obj method-name argument ...)` 

But of course, `send` conflicts with the I/O primitive.

For signal connection, there is no GOOPS analog
- Racket uses
```
(connect obj signal-name handler [#:data data #:cast _user-data])  
```
- The C library uses `g_signal_connect_after` and friends

But, of course, `connect` conflicts with the socket procedure.

I mean, well, I don't hate what you've done here.  I'm concerned that it is novel, and it doesn't map to prior attempts.   

I guess I have two suggestions. 

1. For `modify-signals`, consider more generic and scheme-like `set-signals` or `signal-set`.   `modify-signals` isn't ideal, because it seems to imply that there should have been a `create-signals`.
2. While keeping `with-object`, consider adding, possibly in a `(gi abbrev)` module, either an alias for it that is much shorter, or a `read-hash-extend` syntax.  `send` had the advantage of being quite short.  Perhaps `=>` or `->` could be an alias for `with-object`, or, with `read-hash-extend` you could map `(with-object builder (get-object "window"))` to `#o(builder (get-object "window))` or something similar.

What do you think?

**Comment by LordYuuma** [comment]
> For signal connection, there is no GOOPS analog
Actually, there is. `guile-gnome` (even though it is hopelessly outdated), uses GOOPS methods to define `connect`. Since those methods work with different argument types than the socket methods of Guile, I'm pretty sure they don't interfere with each other, but it doesn't really look nice either.

I chose `modify-signals` because the syntax is quite close to Guix' `modify-phases`, even if there are small differences. But you're right, the naming choice is poor, considering that signals are not really generated in Scheme code on our side. But to be honest, it is nothing but a crutch until I can handle signals in `with-object` (or whatever I decide to name it by then).

I'm open to other naming suggestions for `with-object`. I would even have extended `send` in its stead if that particular name wasn't an issue. I'm not too happy with `=>` and `->` though. The former is used a lot in basic Guile syntax and the latter seems too close to it. Maybe `~>`? I don't think reader extensions make much sense in our case. Letters read like vectors and pretty much any symbol that should realistically show up in code is already used in Guix. I might consider putting an abbreviation in `(gi abbrev)`, but for that, three things must happen:
1. We really can't settle on a better name.
2. We use an alias, that can't reasonably be defined in `(gi)` itself.
3. We no longer use `(gi ...)` for typelib modules and instead can use them for features properly.

If we **do** use feature modules, we should also reevaluate how the current components of gi can be split up into multiple modules.

**Comment by spk121** [comment]
Oh, are you one of the Guix people?  What name do you go by there?

If the goal is converge all methods and signals into a grand unified `with-object` syntax...

You have your five signal primitives: `connect`, `connect-after`, `remove`, `block`, `unblock`. There are Gtk methods also called `connect` or `remove`, like for `GtkAccelGroup`.  But `signal:connect`, `signal:remove`, etc are not methods. Given that, you could use those as pseudo-methods in `with-object`

```
(modify-signals app (connect activate (fire-signal 1)))
(with-object app (run 0 '()))
→
(with-object app (signal:connect activate (fire-signal 1))
        (run 0 '()))
```
For brevity, `using` is a bit shorter than `with-object` and it seems to be non-overloaded. And the
`signal` in `signal:connect` could be removed
```
(modify-signals app (connect activate (fire-signal 1)))
(with-object app (run 0 '()))
→
(using app (:connect activate (fire-signal 1))
        (run 0 '()))
```
What do you think?

**Comment by LordYuuma** [comment]
To say, that I'm one of the Guix people is a bit of a stretch. As of now, I merely use Guix, but I am somewhat inspired by it and do not wish to produce clashes (what if someone wanted to write a graphical frontend for guix using this package?)

I already thought about these collisions, and the solution I've arrived at, is to use the exclamation mark, (e.g. `connect!`), since all of these primitives are in some way or another destructive. I'm currently working on the documentation and will push this change soon.

I can see the appeal of `using`, but I'm not 100% sure if that's the word we want to use. For one, using has a totally different meaning in C++, whose semantics are arguably closer to C's than Scheme's are. The word `use` is also used in a different context in Guile, namely `use-modules`, `use-srfis`, our `use-typelibs` and funnily enough the predicate `using-readline?`

**Comment by spk121** [comment]
I used the modified API in janneke's guimax, which was written using `send` and `connect`.
I ended up with this [gi.scm](https://gitlab.com/spk121/guimax/blob/master/guimax/editor/gi.scm)
It seems okay.
I'll merge this branch tomorrow when I merge patches in guimax, so they can stay synced.

**Comment by LordYuuma** [comment]
You may want to add a `(put fn 'scheme-indent-function 1)` into your .dir-locals.el for the functions `'create` `'with-objects`, `'connect!` and `connect-after!`. That's what I use in this library. By the way, should we add a .dir-locals.el here?

**Comment by spk121** [comment]
A .dir-locals.el would keep it looking more professional.  I'm pretty naïve in how I use emacs, so I always forget about such things.

**Pull request merged**
