### PR TITLE
Guile 3.0.4

### PR DESCRIPTION
**Pull request by LordYuuma**
Adapts Guile-GI to changes in the bitvector API, that would otherwise raise deprecation warnings.

### CODE REVIEW

**Comment by spk121** [comment]
Should the conditional
```
SCM_MAJOR_VERSION == 3 && SCM_MINOR_VERSION == 0 && SCM_MICRO_VERSION < 4
```
be something like
```
(SCM_MAJOR_VERSION <= 2) || (SCM_MAJOR_VERSION == 3 && SCM_MINOR_VERSION == 0 && SCM_MICRO_VERSION < 4)
```
?

But that implies the question of whether to keep `guile-gi` compatible with Guile 2.x...

**Comment by LordYuuma** [comment]
Good catch, I haven't actually tested Guile 2.x.  My personal intuition is that this section will only work for Guile 3.0.y, 2(?) <= y < 4, because part of the new bitvector API already exists there and only this #define needs to be made.  IOW it would probably be wiser to have 

```c
#if SCM_MAJOR_VERSION < 3
#elif SCM_MAJOR_VERSION == 3
#if SCM_MINOR_VERSION...
#endif 
#endif
```

We should probably get our CI running for both 2.2 and 3.0 if we want to ensure backwards compatibility. So first address #59 and then merge this, WDYT?

**Comment by LordYuuma** [comment]
It turns out the suggestion you've made back in October works just fine.

**Comment by spk121** [comment]
Looks good to me.

**Pull request merged**
